baseUrlPikabu=https://pikabu.ru/
baseUrlGoogle=https://www.google.com/
baseUrlPobeda=https://www.flypobeda.ru/
browser.type=chrome
browser.width=1920
browser.height=1080
browser.headless=false
timeout=6000
pageLoadTimeout=30000
screenshots=true
savePageSource=true
reportsFolder=build/reports/test